### PR TITLE
[Bug] CLI Fixes

### LINKED ISSUE #634: [Bug] Kibana upload getting unauthorized error
**Description:**
It is impossible to upload rules to a internally or locally hosted instance by using the Python script.
The cause seems to be one of the parameters in line 118 of the /detection-rules/kibana/connector.py file:
 payload = {'params': payload, 'currentURL': '', 'providerType': 'basic', 'providerName': 'cloud-basic'}

Should the 'ProviderName' be hardcoded here?

**Steps to reproduce the behavior:**
1. Execute the command:
python -m detection_rules kibana --kibana-url xxx -ku username -kp password upload-rule example.toml
where xxx is internally hosted instance of kibana

**Expected behavior:**
Rule successfully uploaded to Kibana

**Actual behavior:**
Python returns an error:
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url:xxx

 - OS: Ubuntu
 - Version: 20.04
 - OS: Centos
 - Version 7.8

### LINKED ISSUE #656: How do I import the rules into Kibana?
Hi guys, I'm trying to import the rules into Kibana but I can't. Can anyone help me with that?

### LINKED ISSUE #772: [FR] Support Self-signed Certificates via CLI
**Is your feature request related to a problem? Please describe.**
It appears that I cannot use the CLI tool due to self signed certificates.

**Describe the solution you'd like**
It would be great to have an option to trust the SSL connection.

I am seeing this error: 
elasticsearch.exceptions.SSLError: ConnectionError([SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:852)) caused by: SSLError([SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:852))

Is there a way to bypass the certificate validation?

### LINKED ISSUE #1067: Update to newest rules in Kibana
Hello,

I just want to update all the rules in Kibana to the rules I see here.
What would be the easiest way to do that?

I tried using the CLI python method but it fails to export the rules to the .ndjson file

Example:
`CLI Error: Unknown rules for rule IDs: rules/macos/credential_access_access_to_browser_credentials_procargs.toml`

using the -d option results in a strange error:

```
root@fort-noggs-s2ubntLT:/etc/elk_rules_update/detection-rules# python3 -m detection_rules export-rules -d rules/macos/ -o expooort.ndjson -s -r

█▀▀▄ ▄▄▄ ▄▄▄ ▄▄▄ ▄▄▄ ▄▄▄ ▄▄▄ ▄▄▄ ▄   ▄      █▀▀▄ ▄  ▄ ▄   ▄▄▄ ▄▄▄
█  █ █▄▄  █  █▄▄ █    █   █  █ █ █▀▄ █      █▄▄▀ █  █ █   █▄▄ █▄▄
█▄▄▀ █▄▄  █  █▄▄ █▄▄  █  ▄█▄ █▄█ █ ▀▄█      █ ▀▄ █▄▄█ █▄▄ █▄▄ ▄▄█

Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/etc/elk_rules_update/detection-rules/detection_rules/__main__.py", line 34, in <module>
    main()
  File "/etc/elk_rules_update/detection-rules/detection_rules/__main__.py", line 31, in main
    root(prog_name="detection_rules")
  File "/usr/lib/python3/dist-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3/dist-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3/dist-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/etc/elk_rules_update/detection-rules/detection_rules/main.py", line 246, in export_rules
    rule.contents['rule_id'] = str(uuid4())
TypeError: 'TOMLRuleContents' object does not support item assignment

```
As you can see I already tried the -s -r options.

I also tried to upload the rules directly to Kibana but that resulted in another error:

`python3 -m detection_rules kibana -ku elastic -kp verygoodpw --kibana-url http://192.168.178.83:5601 upload-rule rule/macos/*.toml`
[...]
`requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: http://192.168.178.83:5601/internal/security/login`

Why is this so hard? Am I overseeing something?

Btw. I have the standalone version (non cloud) if this is important.

### LINKED ISSUE #1072: [Bug] Not able to import rules with import-rules command
**Describe the bug**
Not able to import rules 

**To Reproduce**
1. install python 3.8 on centos machine
2. Install dependencies in requirement.txt
3. Run command: python3.8 -m detection_rules import-rules -d rules/windows recieving above error
4. IndexError: list index out of range

**Expected behavior**
Successfully import multiple rules

**Screenshots**
Screenshot 2021-03-31 120147

**Desktop (please complete the following information):**
 - OS: centos
 - Version: 8.3

**Additional context**
Please help me to resolve this error

### LINKED ISSUE #1472: [Bug] view-rule passes path as string
**Describe the bug**
When using the view-rule command the program crashes with a stack trace:
```
█▀▀▄ ▄▄▄ ▄▄▄ ▄▄▄ ▄▄▄ ▄▄▄ ▄▄▄ ▄▄▄ ▄   ▄      █▀▀▄ ▄  ▄ ▄   ▄▄▄ ▄▄▄
█  █ █▄▄  █  █▄▄ █    █   █  █ █ █▀▄ █      █▄▄▀ █  █ █   █▄▄ █▄▄
█▄▄▀ █▄▄  █  █▄▄ █▄▄  █  ▄█▄ █▄█ █ ▀▄█      █ ▀▄ █▄▄█ █▄▄ █▄▄ ▄▄█

rules/network/command_and_control_cobalt_strike_beacon.toml
Error loading rule in rules/network/command_and_control_cobalt_strike_beacon.toml
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/code/git/detection-rules/detection_rules/__main__.py", line 34, in <module>
    main()
  File "/home/code/git/detection-rules/detection_rules/__main__.py", line 31, in main
    root(prog_name="detection_rules")
  File "/home/code/git/detection-rules/env/detection-rules-build/lib/python3.8/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/code/git/detection-rules/env/detection-rules-build/lib/python3.8/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/code/git/detection-rules/env/detection-rules-build/lib/python3.8/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/code/git/detection-rules/env/detection-rules-build/lib/python3.8/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/code/git/detection-rules/env/detection-rules-build/lib/python3.8/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/code/git/detection-rules/env/detection-rules-build/lib/python3.8/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/code/git/detection-rules/detection_rules/main.py", line 164, in view_rule
    rule = RuleCollection().load_file(rule_file)
  File "/home/code/git/detection-rules/detection_rules/rule_loader.py", line 209, in load_file
    path = path.resolve()
AttributeError: 'str' object has no attribute 'resolve'
```

**To Reproduce**
`$ env/detection-rules-build/bin/python -m detection_rules view-rule rules/network/command_and_control_cobalt_strike_beacon.toml`

**Expected behavior**
Show the rule content

**Desktop (please complete the following information):**
 - OS: Ubuntu 
 - Version: 20.04

**Additional context**

The problem is in `main.py`. We could replace:
```
rule = RuleCollection().load_file(rule_file)
```

with:
```
rule = RuleCollection().load_file(Path(rule_file))
```

### PR DESCRIPTION
**Pull request by brokensound77**
## Issues
resolves #1472
resolves #1072 - `import-rules` command not working
resolves #1067 - kibana auth for non-cloud; `export-rules` command
resolves #772  - self signed certs for es and Kibana
resolves #656  - kibana auth for non-cloud
resolves #634 - kibana auth for non-cloud

## Summary
This resolves multiple existing bugs which were introduced during the refactors, primarily in the CLI and kibana client.

The history got muddled due to upstream changes, but the initial commit log reflects the primary commands targeted for fixes

### For reviewers
If there are any other issues which are resolved by this, please add

Also, if there are any other existing bugs which may be within scope, we can incorporate that as well

### CODE REVIEW

**Comment by rw-access** [comment]
Thanks for taking care of this and some of the issues that were caused by #1029 and #1063.
Let me know when you're ready for us to get this through and un-break things.

**Comment by brokensound77** [comment]
Maybe a double check on any issues with backporting @rw-access

File: detection_rules/devtools.py [hunk 1]
```diff
@@ -391,25 +398,25 @@ def deprecate_rule(ctx: click.Context, rule_file: str):
 
     version_info = load_versions()
     rule_file = Path(rule_file)
-    contents = pytoml.loads(rule_file.read_text())
+    contents = TOMLRuleContents.from_dict(pytoml.loads(rule_file.read_text()))
```
Comment (rw-access) [inline detection_rules/devtools.py:401]: I think RuleCollection can do TOML now?

File: detection_rules/devtools.py [hunk 2]
```diff
@@ -391,25 +398,25 @@ def deprecate_rule(ctx: click.Context, rule_file: str):
...
         ctx.exit()
 
     today = time.strftime('%Y/%m/%d')
 
-    new_meta = dataclasses.replace(rule.contents.metadata,
-                                   updated_date=today,
-                                   deprecation_date=today,
-                                   maturity='deprecated')
-    contents = dataclasses.replace(rule.contents, metadata=new_meta)
+    new_meta = {
```
Comment (rw-access) [inline detection_rules/devtools.py:411]: not a big fan of this change/function. it loses all type information, plus i'm not sure what the need/improvement was

File: detection_rules/kbwrap.py [hunk 3]
```diff
@@ -27,11 +30,19 @@ def get_kibana_client(cloud_id, kibana_url, kibana_user, kibana_password, kibana
         kibana_user = kibana_user or click.prompt("kibana_user")
         kibana_password = kibana_password or click.prompt("kibana_password", hide_input=True)
 
-    with Kibana(cloud_id=cloud_id, kibana_url=kibana_url, **kwargs) as kibana:
+    with Kibana(cloud_id=cloud_id, kibana_url=kibana_url, space=space, verify=not no_verify, **kwargs) as kibana:
         if kibana_cookie:
             kibana.add_cookie(kibana_cookie)
```
Comment (rw-access) [inline detection_rules/kbwrap.py:35]: since it's a big else, `return` here and flatten out the `else`

File: detection_rules/kbwrap.py [hunk 4]
```diff
@@ -78,8 +88,22 @@ def upload_rule(ctx, rules, replace_id):
...
     with kibana:
-        rules = RuleResource.bulk_create(api_payloads)
-        click.echo(f"Successfully uploaded {len(rules)} rules")
+        results = RuleResource.bulk_create(api_payloads)
+
+    success = []
+    errors = []
+    for result in results:
+        if 'error' in result:
+            errors.append(f'{result["rule_id"]} - {result["error"]["message"]}')
```
Comment (rw-access) [inline detection_rules/kbwrap.py:97]: just print here instead

File: detection_rules/main.py [hunk 5]
```diff
@@ -47,7 +45,7 @@ def root(ctx, debug):
               help='Type of rule to create')
 def create_rule(path, config, required_only, rule_type):
```
Comment (rw-access) [inline detection_rules/main.py:46]: type hint here, if it's not supposed to be  a `Path`. or make it `Path` and fix the caller

File: detection_rules/main.py [hunk 6]
```diff
@@ -155,17 +153,56 @@ def mass_update(ctx, query, metadata, language, field):
 
 
 @root.command('view-rule')
-@click.argument('rule-file')
+@click.argument('rule-file', type=Path)
 @click.option('--api-format/--rule-format', default=True, help='Print the rule in final api or rule format')
 @click.pass_context
-def view_rule(ctx, rule_file, api_format):
+def view_rule(ctx, rule_file, api_format, verbose=True):
```
Comment (rw-access) [inline detection_rules/main.py:159]: calling this function without `verbose` is a no-op.
i would leave it.

if you want to get the pretty format as a string, then do that.
can add `TOMLRule.as_toml`  and `TOMLRule.as_api_json` if you want

File: detection_rules/main.py [hunk 7]
```diff
@@ -158,14 +156,53 @@ def mass_update(ctx, query, metadata, language, field):
...
+    outfile = outfile.with_suffix('.ndjson')
+    unsupported = []
+
+    if downgrade_version:
+        if skip_unsupported:
+            output_lines = []
+
+            for rule in rules:
+                try:
+                    output_lines.append(json.dumps(downgrade_contents_from_rule(rule, downgrade_version),
```
[the remark this answers is not in the document]
Comment (rw-access) [reply detection_rules/main.py:186]: shouldn't this be `rule.as_api_format`? does that cause errors?

File: detection_rules/main.py [hunk 8]
```diff
@@ -180,25 +217,22 @@ def view_rule(ctx, rule_file, api_format):
...
-    from .packaging import Package
-
     assert len(rules) > 0, "No rules found"
 
     if replace_id:
-        # if we need to replace the id, take each rule object and create a copy
-        # of it, with only the rule_id field changed
-        old_rules = rules
-        rules = RuleCollection()
+        from uuid import uuid4
```
Comment (rw-access) [inline detection_rules/main.py:223]: global import

File: detection_rules/main.py [hunk 9]
```diff
@@ -180,25 +217,22 @@ def view_rule(ctx, rule_file, api_format):
...
+
+        new_rules = []
+        for rule in rules:
+            new_rules.append(rule.new(data=dict(rule_id=str(uuid4()))))
```
Comment (rw-access) [inline detection_rules/main.py:227]: put back if you can please

File: detection_rules/misc.py [hunk 10]
```diff
@@ -279,14 +279,18 @@ def getdefault(name):
         'kibana_password': click.Option(['--kibana-password', '-kp'], default=getdefault('kibana_password')),
         'kibana_url': click.Option(['--kibana-url'], default=getdefault('kibana_url')),
         'kibana_user': click.Option(['--kibana-user', '-ku'], default=getdefault('kibana_user')),
-        'space': click.Option(['--space'], default=None, help='Kibana space')
+        'provider_type': click.Option(['--provider-type'], default=getdefault('provider_type')),
+        'provider_name': click.Option(['--provider-name'], default=getdefault('provider_name')),
+        'space': click.Option(['--space'], default=None, help='Kibana space'),
+        'no_verify': click.Option(['--no-verify'], default=getdefault('no_verify'))
```
Comment (rw-access) [inline detection_rules/misc.py:285]: too vague, maybe?
```suggestion
        'ignore_ssl_errors': click.Option(['--ignore-ssl-errors'], default=getdefault('ignore_ssl_errors'))
```

File: detection_rules/kbwrap.py (hunk 4 above)
Comment (brokensound77) [reply detection_rules/kbwrap.py:97]: the way it is groups failures and successes rather than interlacing them as they occur

File: detection_rules/main.py (hunk 7 above)
[the remark this answers is not in the document]
Comment (brokensound77) [reply detection_rules/main.py:186]: I am not following ❓

File: detection_rules/devtools.py (hunk 2 above)
Comment (brokensound77) [reply detection_rules/devtools.py:652]: for clarification, are you referring to the `Rule.new` method? Can you describe what you want changed?

File: detection_rules/main.py (hunk 7 above)
[the remark this answers is not in the document]
Comment (brokensound77) [reply detection_rules/main.py:186]: the `downgrade_contents_from_rule` function extracts the contents using the `as_api_format` method

File: detection_rules/main.py (hunk 9 above)
Comment (brokensound77) [reply detection_rules/main.py:225]: Functionality was moved to `_export_rules` since it is shared. Can you elaborate otherwise?

File: detection_rules/main.py (hunk 7 above)
[the remark this answers is not in the document]
Comment (brokensound77) [reply detection_rules/main.py:186]: @rw-access removing this from the `7.13.*` api-schemas resolves the problem

```json
  "additionalProperties": {
        "type": "string"
      },
```

So I wonder if the jsonschema patch is off just a bit. The `additionalProperties` is only in the `7.13.*` and `7.14.*` schemas

File: detection_rules/rule.py [hunk 11]
```diff
@@ -500,6 +501,17 @@ def get_asset(self) -> dict:
         """Generate the relevant fleet compatible asset."""
         return {"id": self.id, "attributes": self.contents.to_api_format(), "type": definitions.SAVED_OBJECT_TYPE}
 
+    def new(self, path: Optional[Path] = None, data: Optional[dict] = None, metadata: Optional[dict] = None):
```
Comment (rw-access) [inline detection_rules/rule.py:504]: I don't personally like this `new` method. One advantage for the switch to dataclasses was type validation, and IMO this erases that. Is there any reason you can't do `dataclasses.replace` from the caller?

File: detection_rules/main.py (hunk 7 above)
[the remark this answers is not in the document]
Comment (rw-access) [reply detection_rules/main.py:186]: It expects a map of string -> string for `meta`.
Instead, just set `"additionalProperties": true` in the files manually and it should do what you want

File: detection_rules/devtools.py (hunk 2 above)
Comment (rw-access) [reply detection_rules/devtools.py:652]: basically instead of the `.new()` function, we should just explicitly call `replace`

File: detection_rules/main.py (hunk 7 above)
[the remark this answers is not in the document]
Comment (brokensound77) [reply detection_rules/main.py:186]: right makes sense. Will the jsonschema patch cause this error every time a new schema is generated though?

File: detection_rules/rule.py (hunk 11 above)
Comment (brokensound77) [reply detection_rules/rule.py:504]: I will revert all the references to this - good point

File: detection_rules/main.py (hunk 7 above)
[the remark this answers is not in the document]
Comment (brokensound77) [reply detection_rules/main.py:186]: I updated the 7.13 and 7.14 api_schemas in ba3e95c0f106bf160d09306d07991b004d6bd9f0 according to #1438 and it resolved the issue

File: detection_rules/devtools.py [hunk 12]
```diff
@@ -596,29 +597,36 @@ def search_rule_prs(ctx, no_loop, query, columns, language, token, threads):
...
         if original_rule_id:
-            rule.metadata['original_rule_id'] = original_rule_id
-            rule.contents['rule_id'] = str(uuid4())
+            new_meta['original_rule_id'] = original_rule_id
+            new_data = {'rule_id': str(uuid4())}
 
-        rule_path = f'pr-{pr.number}-{rule.path}'
-        all_rules[rule_path] = rule.rule_format()
+        rule_path = Path(f'pr-{pr.number}-{rule.path}')
+        contents = dataclasses.replace(rule.contents, metadata=new_meta, data=new_data)
```
Comment (rw-access) [inline detection_rules/devtools.py:625]: this won't work, because you're replacing the .metadata and .data dataclasses with dicts.
should be more like: 
 `data=dataclasses.replace(rule.contents.data, rule_id=str(uuid4())`

Comment (rw-access) [inline detection_rules/devtools.py:625]: do you think `new_meta` should go in `metadata.extended`? that takes an arbitrary dict, seems like a great place for it

**Review by rw-access — APPROVED** [review]
LGTM thanks for the dataclasses.replace fixes

**Comment by nicpenning** [comment]
Try --no-verify. Not sure what comma f is needed but looking at the code, that may work.
